library(usethis)
use_git_config(user.name = "Runtian Su", user.email = "pmxrs6@nottingham.ac.uk")
edit_git_config()
use_git()
library(usethis)
create_github_token()

library(gitcreds)
gitcreds_set()
use_github()
